source 'https://rubygems.org'

gem 'test-unit'
gem 'activerecord', '~> 6.0'

#gem 'cubrid'
#gem 'cubrid', path: '/opt/cubrid/cubrid-ruby'
gem 'cubrid', github: 'CUBRID/cubrid-ruby'

#gem 'activerecord-cubrid2-adapter', path: '../'
gem 'activerecord-cubrid2-adapter'
